FROM debian:bullseye-20230227-slim

ADD ca-certificates.crt /etc/ssl/certs/
RUN mkdir /dsc
COPY dsc /dsc/
COPY assets /dsc/assets
COPY preStop.sh /dsc/
RUN chmod a+x /dsc/preStop.sh
COPY postStart.sh /dsc/
RUN chmod a+x /dsc/postStart.sh

WORKDIR /dsc
ENTRYPOINT exec ./dsc