// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: client_server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2S_MsgID_MsgID int32

const (
	C2S_MsgID_Ping           C2S_MsgID_MsgID = 0
	C2S_MsgID_LocalLogin     C2S_MsgID_MsgID = 1
	C2S_MsgID_AuthLogin      C2S_MsgID_MsgID = 2
	C2S_MsgID_CreateRealm    C2S_MsgID_MsgID = 3
	C2S_MsgID_JoinRealm      C2S_MsgID_MsgID = 4
	C2S_MsgID_QuickJoinRealm C2S_MsgID_MsgID = 5
	C2S_MsgID_StartRealm     C2S_MsgID_MsgID = 6
	C2S_MsgID_QuitRealmTeam  C2S_MsgID_MsgID = 7
)

// Enum value maps for C2S_MsgID_MsgID.
var (
	C2S_MsgID_MsgID_name = map[int32]string{
		0: "Ping",
		1: "LocalLogin",
		2: "AuthLogin",
		3: "CreateRealm",
		4: "JoinRealm",
		5: "QuickJoinRealm",
		6: "StartRealm",
		7: "QuitRealmTeam",
	}
	C2S_MsgID_MsgID_value = map[string]int32{
		"Ping":           0,
		"LocalLogin":     1,
		"AuthLogin":      2,
		"CreateRealm":    3,
		"JoinRealm":      4,
		"QuickJoinRealm": 5,
		"StartRealm":     6,
		"QuitRealmTeam":  7,
	}
)

func (x C2S_MsgID_MsgID) Enum() *C2S_MsgID_MsgID {
	p := new(C2S_MsgID_MsgID)
	*p = x
	return p
}

func (x C2S_MsgID_MsgID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (C2S_MsgID_MsgID) Descriptor() protoreflect.EnumDescriptor {
	return file_client_server_proto_enumTypes[0].Descriptor()
}

func (C2S_MsgID_MsgID) Type() protoreflect.EnumType {
	return &file_client_server_proto_enumTypes[0]
}

func (x C2S_MsgID_MsgID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use C2S_MsgID_MsgID.Descriptor instead.
func (C2S_MsgID_MsgID) EnumDescriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{0, 0}
}

type S2C_MsgID_MsgID int32

const (
	S2C_MsgID_Pong          S2C_MsgID_MsgID = 0
	S2C_MsgID_LoginOK       S2C_MsgID_MsgID = 1
	S2C_MsgID_LoginFail     S2C_MsgID_MsgID = 2
	S2C_MsgID_JoinRealmOK   S2C_MsgID_MsgID = 3
	S2C_MsgID_JoinRealmFail S2C_MsgID_MsgID = 4
)

// Enum value maps for S2C_MsgID_MsgID.
var (
	S2C_MsgID_MsgID_name = map[int32]string{
		0: "Pong",
		1: "LoginOK",
		2: "LoginFail",
		3: "JoinRealmOK",
		4: "JoinRealmFail",
	}
	S2C_MsgID_MsgID_value = map[string]int32{
		"Pong":          0,
		"LoginOK":       1,
		"LoginFail":     2,
		"JoinRealmOK":   3,
		"JoinRealmFail": 4,
	}
)

func (x S2C_MsgID_MsgID) Enum() *S2C_MsgID_MsgID {
	p := new(S2C_MsgID_MsgID)
	*p = x
	return p
}

func (x S2C_MsgID_MsgID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (S2C_MsgID_MsgID) Descriptor() protoreflect.EnumDescriptor {
	return file_client_server_proto_enumTypes[1].Descriptor()
}

func (S2C_MsgID_MsgID) Type() protoreflect.EnumType {
	return &file_client_server_proto_enumTypes[1]
}

func (x S2C_MsgID_MsgID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use S2C_MsgID_MsgID.Descriptor instead.
func (S2C_MsgID_MsgID) EnumDescriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{9, 0}
}

//*
//client to server id
type C2S_MsgID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2S_MsgID) Reset() {
	*x = C2S_MsgID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_MsgID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_MsgID) ProtoMessage() {}

func (x *C2S_MsgID) ProtoReflect() protoreflect.Message {
	mi := &file_client_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_MsgID.ProtoReflect.Descriptor instead.
func (*C2S_MsgID) Descriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{0}
}

//*
//C2S_MsgIDPing
type PingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientTime int64 `protobuf:"varint,1,opt,name=clientTime,proto3" json:"clientTime,omitempty"` ///毫秒
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{1}
}

func (x *PingReq) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

//*
//C2S_MsgIDLocalLogin
type LocalLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *LocalLoginReq) Reset() {
	*x = LocalLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalLoginReq) ProtoMessage() {}

func (x *LocalLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalLoginReq.ProtoReflect.Descriptor instead.
func (*LocalLoginReq) Descriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{2}
}

func (x *LocalLoginReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

//*
//C2S_MsgIDAuthLogin
type AuthLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID string `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
}

func (x *AuthLoginReq) Reset() {
	*x = AuthLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLoginReq) ProtoMessage() {}

func (x *AuthLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLoginReq.ProtoReflect.Descriptor instead.
func (*AuthLoginReq) Descriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{3}
}

func (x *AuthLoginReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

//*
//C2S_MsgIDCreateRealm
type CreateRealmReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RealmConfigID string `protobuf:"bytes,1,opt,name=realmConfigID,proto3" json:"realmConfigID,omitempty"`
}

func (x *CreateRealmReq) Reset() {
	*x = CreateRealmReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRealmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRealmReq) ProtoMessage() {}

func (x *CreateRealmReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRealmReq.ProtoReflect.Descriptor instead.
func (*CreateRealmReq) Descriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRealmReq) GetRealmConfigID() string {
	if x != nil {
		return x.RealmConfigID
	}
	return ""
}

//*
//C2S_MsgIDJoinRealm
type JoinRealmReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RealmID string `protobuf:"bytes,1,opt,name=realmID,proto3" json:"realmID,omitempty"`
}

func (x *JoinRealmReq) Reset() {
	*x = JoinRealmReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRealmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRealmReq) ProtoMessage() {}

func (x *JoinRealmReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRealmReq.ProtoReflect.Descriptor instead.
func (*JoinRealmReq) Descriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRealmReq) GetRealmID() string {
	if x != nil {
		return x.RealmID
	}
	return ""
}

//*
//C2S_MsgIDQuickJoinRealm
type QuickJoinRealmReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RealmConfigID string `protobuf:"bytes,1,opt,name=realmConfigID,proto3" json:"realmConfigID,omitempty"`
}

func (x *QuickJoinRealmReq) Reset() {
	*x = QuickJoinRealmReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuickJoinRealmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickJoinRealmReq) ProtoMessage() {}

func (x *QuickJoinRealmReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickJoinRealmReq.ProtoReflect.Descriptor instead.
func (*QuickJoinRealmReq) Descriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{6}
}

func (x *QuickJoinRealmReq) GetRealmConfigID() string {
	if x != nil {
		return x.RealmConfigID
	}
	return ""
}

//*
//C2S_MsgIDStartRealm
type StartRealmReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartRealmReq) Reset() {
	*x = StartRealmReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRealmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRealmReq) ProtoMessage() {}

func (x *StartRealmReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRealmReq.ProtoReflect.Descriptor instead.
func (*StartRealmReq) Descriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{7}
}

//*
//C2S_MsgIDQuitRealmTeam
type QuitRealmTeamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QuitRealmTeamReq) Reset() {
	*x = QuitRealmTeamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitRealmTeamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitRealmTeamReq) ProtoMessage() {}

func (x *QuitRealmTeamReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitRealmTeamReq.ProtoReflect.Descriptor instead.
func (*QuitRealmTeamReq) Descriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{8}
}

//*
//server to client id
type S2C_MsgID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2C_MsgID) Reset() {
	*x = S2C_MsgID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_MsgID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_MsgID) ProtoMessage() {}

func (x *S2C_MsgID) ProtoReflect() protoreflect.Message {
	mi := &file_client_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_MsgID.ProtoReflect.Descriptor instead.
func (*S2C_MsgID) Descriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{9}
}

//*
//S2C_MsgIDPong
type PongResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientTime int64 `protobuf:"varint,1,opt,name=clientTime,proto3" json:"clientTime,omitempty"` ///毫秒
}

func (x *PongResp) Reset() {
	*x = PongResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PongResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResp) ProtoMessage() {}

func (x *PongResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResp.ProtoReflect.Descriptor instead.
func (*PongResp) Descriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{10}
}

func (x *PongResp) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

//*
//S2C_MsgIDLoginOK
type LoginOKResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTime  int64        `protobuf:"varint,1,opt,name=serverTime,proto3" json:"serverTime,omitempty"` ///毫秒
	PlayerModel *PlayerModel `protobuf:"bytes,2,opt,name=playerModel,proto3" json:"playerModel,omitempty"`
}

func (x *LoginOKResp) Reset() {
	*x = LoginOKResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginOKResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginOKResp) ProtoMessage() {}

func (x *LoginOKResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginOKResp.ProtoReflect.Descriptor instead.
func (*LoginOKResp) Descriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{11}
}

func (x *LoginOKResp) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *LoginOKResp) GetPlayerModel() *PlayerModel {
	if x != nil {
		return x.PlayerModel
	}
	return nil
}

//*
//S2C_MsgIDLoginFail
type LoginFAILResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int64 `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
}

func (x *LoginFAILResp) Reset() {
	*x = LoginFAILResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginFAILResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginFAILResp) ProtoMessage() {}

func (x *LoginFAILResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginFAILResp.ProtoReflect.Descriptor instead.
func (*LoginFAILResp) Descriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{12}
}

func (x *LoginFAILResp) GetErrCode() int64 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

//*
//S2C_MsgIDJoinRealmOK
type JoinRealmOKResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RealmConfigID string `protobuf:"bytes,1,opt,name=realmConfigID,proto3" json:"realmConfigID,omitempty"`
	DsAddr        string `protobuf:"bytes,2,opt,name=dsAddr,proto3" json:"dsAddr,omitempty"`
	TeamID        string `protobuf:"bytes,3,opt,name=teamID,proto3" json:"teamID,omitempty"`
}

func (x *JoinRealmOKResp) Reset() {
	*x = JoinRealmOKResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRealmOKResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRealmOKResp) ProtoMessage() {}

func (x *JoinRealmOKResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRealmOKResp.ProtoReflect.Descriptor instead.
func (*JoinRealmOKResp) Descriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{13}
}

func (x *JoinRealmOKResp) GetRealmConfigID() string {
	if x != nil {
		return x.RealmConfigID
	}
	return ""
}

func (x *JoinRealmOKResp) GetDsAddr() string {
	if x != nil {
		return x.DsAddr
	}
	return ""
}

func (x *JoinRealmOKResp) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

//*
//S2C_MsgIDJoinRealmFail
type JoinRealmFailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JoinRealmFailResp) Reset() {
	*x = JoinRealmFailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRealmFailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRealmFailResp) ProtoMessage() {}

func (x *JoinRealmFailResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRealmFailResp.ProtoReflect.Descriptor instead.
func (*JoinRealmFailResp) Descriptor() ([]byte, []int) {
	return file_client_server_proto_rawDescGZIP(), []int{14}
}

var File_client_server_proto protoreflect.FileDescriptor

var file_client_server_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x01, 0x0a, 0x09, 0x43, 0x32, 0x53, 0x5f,
	0x4d, 0x73, 0x67, 0x49, 0x44, 0x22, 0x87, 0x01, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x12,
	0x08, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x75, 0x74,
	0x68, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x4a, 0x6f, 0x69,
	0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x51, 0x75, 0x69, 0x63,
	0x6b, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d,
	0x51, 0x75, 0x69, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x54, 0x65, 0x61, 0x6d, 0x10, 0x07, 0x22,
	0x29, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0d, 0x4c, 0x6f,
	0x63, 0x61, 0x6c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x22, 0x2c, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x22, 0x36, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d,
	0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x61, 0x6c,
	0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x22, 0x28, 0x0a, 0x0c, 0x4a, 0x6f, 0x69,
	0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x61,
	0x6c, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x61, 0x6c,
	0x6d, 0x49, 0x44, 0x22, 0x39, 0x0a, 0x11, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x4a, 0x6f, 0x69, 0x6e,
	0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x61, 0x6c,
	0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x22, 0x0f,
	0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x22,
	0x12, 0x0a, 0x10, 0x51, 0x75, 0x69, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x54, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x22, 0x5e, 0x0a, 0x09, 0x53, 0x32, 0x43, 0x5f, 0x4d, 0x73, 0x67, 0x49, 0x44,
	0x22, 0x51, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x6f, 0x6e,
	0x67, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4f, 0x4b, 0x10, 0x01,
	0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x10, 0x02, 0x12,
	0x0f, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x4f, 0x4b, 0x10, 0x03,
	0x12, 0x11, 0x0a, 0x0d, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x46, 0x61, 0x69,
	0x6c, 0x10, 0x04, 0x22, 0x2a, 0x0a, 0x08, 0x50, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x60, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4f, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x31,
	0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x22, 0x29, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x41, 0x49, 0x4c, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x67, 0x0a, 0x0f,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x4f, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x24, 0x0a, 0x0d, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x73, 0x41, 0x64, 0x64, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x73, 0x41, 0x64, 0x64, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x65, 0x61, 0x6d, 0x49, 0x44, 0x22, 0x13, 0x0a, 0x11, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61,
	0x6c, 0x6d, 0x46, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_client_server_proto_rawDescOnce sync.Once
	file_client_server_proto_rawDescData = file_client_server_proto_rawDesc
)

func file_client_server_proto_rawDescGZIP() []byte {
	file_client_server_proto_rawDescOnce.Do(func() {
		file_client_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_server_proto_rawDescData)
	})
	return file_client_server_proto_rawDescData
}

var file_client_server_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_client_server_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_client_server_proto_goTypes = []interface{}{
	(C2S_MsgID_MsgID)(0),      // 0: pb.C2S_MsgID.MsgID
	(S2C_MsgID_MsgID)(0),      // 1: pb.S2C_MsgID.MsgID
	(*C2S_MsgID)(nil),         // 2: pb.C2S_MsgID
	(*PingReq)(nil),           // 3: pb.PingReq
	(*LocalLoginReq)(nil),     // 4: pb.LocalLoginReq
	(*AuthLoginReq)(nil),      // 5: pb.AuthLoginReq
	(*CreateRealmReq)(nil),    // 6: pb.CreateRealmReq
	(*JoinRealmReq)(nil),      // 7: pb.JoinRealmReq
	(*QuickJoinRealmReq)(nil), // 8: pb.QuickJoinRealmReq
	(*StartRealmReq)(nil),     // 9: pb.StartRealmReq
	(*QuitRealmTeamReq)(nil),  // 10: pb.QuitRealmTeamReq
	(*S2C_MsgID)(nil),         // 11: pb.S2C_MsgID
	(*PongResp)(nil),          // 12: pb.PongResp
	(*LoginOKResp)(nil),       // 13: pb.LoginOKResp
	(*LoginFAILResp)(nil),     // 14: pb.LoginFAILResp
	(*JoinRealmOKResp)(nil),   // 15: pb.JoinRealmOKResp
	(*JoinRealmFailResp)(nil), // 16: pb.JoinRealmFailResp
	(*PlayerModel)(nil),       // 17: pb.PlayerModel
}
var file_client_server_proto_depIdxs = []int32{
	17, // 0: pb.LoginOKResp.playerModel:type_name -> pb.PlayerModel
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_client_server_proto_init() }
func file_client_server_proto_init() {
	if File_client_server_proto != nil {
		return
	}
	file_player_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_client_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_MsgID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRealmReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRealmReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuickJoinRealmReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRealmReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitRealmTeamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_MsgID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PongResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginOKResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginFAILResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_server_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRealmOKResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_server_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRealmFailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_server_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_server_proto_goTypes,
		DependencyIndexes: file_client_server_proto_depIdxs,
		EnumInfos:         file_client_server_proto_enumTypes,
		MessageInfos:      file_client_server_proto_msgTypes,
	}.Build()
	File_client_server_proto = out.File
	file_client_server_proto_rawDesc = nil
	file_client_server_proto_goTypes = nil
	file_client_server_proto_depIdxs = nil
}
