// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: server_rpc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameDscDSClient is the client API for GameDscDS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameDscDSClient interface {
	CreateDS(ctx context.Context, in *RpcCreateDSReq, opts ...grpc.CallOption) (*RpcCreateDSResp, error)
	RemoveDS(ctx context.Context, in *RpcRemoveDSReq, opts ...grpc.CallOption) (*RpcRemoveDSResp, error)
}

type gameDscDSClient struct {
	cc grpc.ClientConnInterface
}

func NewGameDscDSClient(cc grpc.ClientConnInterface) GameDscDSClient {
	return &gameDscDSClient{cc}
}

func (c *gameDscDSClient) CreateDS(ctx context.Context, in *RpcCreateDSReq, opts ...grpc.CallOption) (*RpcCreateDSResp, error) {
	out := new(RpcCreateDSResp)
	err := c.cc.Invoke(ctx, "/pb.GameDscDS/CreateDS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameDscDSClient) RemoveDS(ctx context.Context, in *RpcRemoveDSReq, opts ...grpc.CallOption) (*RpcRemoveDSResp, error) {
	out := new(RpcRemoveDSResp)
	err := c.cc.Invoke(ctx, "/pb.GameDscDS/RemoveDS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameDscDSServer is the server API for GameDscDS service.
// All implementations must embed UnimplementedGameDscDSServer
// for forward compatibility
type GameDscDSServer interface {
	CreateDS(context.Context, *RpcCreateDSReq) (*RpcCreateDSResp, error)
	RemoveDS(context.Context, *RpcRemoveDSReq) (*RpcRemoveDSResp, error)
	mustEmbedUnimplementedGameDscDSServer()
}

// UnimplementedGameDscDSServer must be embedded to have forward compatible implementations.
type UnimplementedGameDscDSServer struct {
}

func (UnimplementedGameDscDSServer) CreateDS(context.Context, *RpcCreateDSReq) (*RpcCreateDSResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDS not implemented")
}
func (UnimplementedGameDscDSServer) RemoveDS(context.Context, *RpcRemoveDSReq) (*RpcRemoveDSResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDS not implemented")
}
func (UnimplementedGameDscDSServer) mustEmbedUnimplementedGameDscDSServer() {}

// UnsafeGameDscDSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameDscDSServer will
// result in compilation errors.
type UnsafeGameDscDSServer interface {
	mustEmbedUnimplementedGameDscDSServer()
}

func RegisterGameDscDSServer(s grpc.ServiceRegistrar, srv GameDscDSServer) {
	s.RegisterService(&GameDscDS_ServiceDesc, srv)
}

func _GameDscDS_CreateDS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcCreateDSReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameDscDSServer).CreateDS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GameDscDS/CreateDS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameDscDSServer).CreateDS(ctx, req.(*RpcCreateDSReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameDscDS_RemoveDS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcRemoveDSReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameDscDSServer).RemoveDS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GameDscDS/RemoveDS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameDscDSServer).RemoveDS(ctx, req.(*RpcRemoveDSReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GameDscDS_ServiceDesc is the grpc.ServiceDesc for GameDscDS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameDscDS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GameDscDS",
	HandlerType: (*GameDscDSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDS",
			Handler:    _GameDscDS_CreateDS_Handler,
		},
		{
			MethodName: "RemoveDS",
			Handler:    _GameDscDS_RemoveDS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server_rpc.proto",
}

// DsaDscADSClient is the client API for DsaDscADS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DsaDscADSClient interface {
	StreamService(ctx context.Context, opts ...grpc.CallOption) (DsaDscADS_StreamServiceClient, error)
}

type dsaDscADSClient struct {
	cc grpc.ClientConnInterface
}

func NewDsaDscADSClient(cc grpc.ClientConnInterface) DsaDscADSClient {
	return &dsaDscADSClient{cc}
}

func (c *dsaDscADSClient) StreamService(ctx context.Context, opts ...grpc.CallOption) (DsaDscADS_StreamServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &DsaDscADS_ServiceDesc.Streams[0], "/pb.DsaDscADS/StreamService", opts...)
	if err != nil {
		return nil, err
	}
	x := &dsaDscADSStreamServiceClient{stream}
	return x, nil
}

type DsaDscADS_StreamServiceClient interface {
	Send(*StreamClientEvent) error
	Recv() (*StreamServerEvent, error)
	grpc.ClientStream
}

type dsaDscADSStreamServiceClient struct {
	grpc.ClientStream
}

func (x *dsaDscADSStreamServiceClient) Send(m *StreamClientEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dsaDscADSStreamServiceClient) Recv() (*StreamServerEvent, error) {
	m := new(StreamServerEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DsaDscADSServer is the server API for DsaDscADS service.
// All implementations must embed UnimplementedDsaDscADSServer
// for forward compatibility
type DsaDscADSServer interface {
	StreamService(DsaDscADS_StreamServiceServer) error
	mustEmbedUnimplementedDsaDscADSServer()
}

// UnimplementedDsaDscADSServer must be embedded to have forward compatible implementations.
type UnimplementedDsaDscADSServer struct {
}

func (UnimplementedDsaDscADSServer) StreamService(DsaDscADS_StreamServiceServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamService not implemented")
}
func (UnimplementedDsaDscADSServer) mustEmbedUnimplementedDsaDscADSServer() {}

// UnsafeDsaDscADSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DsaDscADSServer will
// result in compilation errors.
type UnsafeDsaDscADSServer interface {
	mustEmbedUnimplementedDsaDscADSServer()
}

func RegisterDsaDscADSServer(s grpc.ServiceRegistrar, srv DsaDscADSServer) {
	s.RegisterService(&DsaDscADS_ServiceDesc, srv)
}

func _DsaDscADS_StreamService_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DsaDscADSServer).StreamService(&dsaDscADSStreamServiceServer{stream})
}

type DsaDscADS_StreamServiceServer interface {
	Send(*StreamServerEvent) error
	Recv() (*StreamClientEvent, error)
	grpc.ServerStream
}

type dsaDscADSStreamServiceServer struct {
	grpc.ServerStream
}

func (x *dsaDscADSStreamServiceServer) Send(m *StreamServerEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dsaDscADSStreamServiceServer) Recv() (*StreamClientEvent, error) {
	m := new(StreamClientEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DsaDscADS_ServiceDesc is the grpc.ServiceDesc for DsaDscADS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DsaDscADS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DsaDscADS",
	HandlerType: (*DsaDscADSServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamService",
			Handler:       _DsaDscADS_StreamService_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server_rpc.proto",
}
