// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: server_rpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcHeader_RoomErrEnum int32

const (
	RpcHeader_OK            RpcHeader_RoomErrEnum = 0
	RpcHeader_ReqParamError RpcHeader_RoomErrEnum = 1
)

// Enum value maps for RpcHeader_RoomErrEnum.
var (
	RpcHeader_RoomErrEnum_name = map[int32]string{
		0: "OK",
		1: "ReqParamError",
	}
	RpcHeader_RoomErrEnum_value = map[string]int32{
		"OK":            0,
		"ReqParamError": 1,
	}
)

func (x RpcHeader_RoomErrEnum) Enum() *RpcHeader_RoomErrEnum {
	p := new(RpcHeader_RoomErrEnum)
	*p = x
	return p
}

func (x RpcHeader_RoomErrEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcHeader_RoomErrEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_server_rpc_proto_enumTypes[0].Descriptor()
}

func (RpcHeader_RoomErrEnum) Type() protoreflect.EnumType {
	return &file_server_rpc_proto_enumTypes[0]
}

func (x RpcHeader_RoomErrEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcHeader_RoomErrEnum.Descriptor instead.
func (RpcHeader_RoomErrEnum) EnumDescriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{0, 0}
}

type RpcHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    RpcHeader_RoomErrEnum `protobuf:"varint,1,opt,name=ret,proto3,enum=pb.RpcHeader_RoomErrEnum" json:"ret,omitempty"`
	Errmsg string                `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
}

func (x *RpcHeader) Reset() {
	*x = RpcHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcHeader) ProtoMessage() {}

func (x *RpcHeader) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcHeader.ProtoReflect.Descriptor instead.
func (*RpcHeader) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RpcHeader) GetRet() RpcHeader_RoomErrEnum {
	if x != nil {
		return x.Ret
	}
	return RpcHeader_OK
}

func (x *RpcHeader) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type StreamClientEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CEvent *anypb.Any `protobuf:"bytes,1,opt,name=CEvent,proto3" json:"CEvent,omitempty"`
}

func (x *StreamClientEvent) Reset() {
	*x = StreamClientEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamClientEvent) ProtoMessage() {}

func (x *StreamClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamClientEvent.ProtoReflect.Descriptor instead.
func (*StreamClientEvent) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *StreamClientEvent) GetCEvent() *anypb.Any {
	if x != nil {
		return x.CEvent
	}
	return nil
}

type StreamServerEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SEvent *anypb.Any `protobuf:"bytes,1,opt,name=SEvent,proto3" json:"SEvent,omitempty"`
}

func (x *StreamServerEvent) Reset() {
	*x = StreamServerEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamServerEvent) ProtoMessage() {}

func (x *StreamServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamServerEvent.ProtoReflect.Descriptor instead.
func (*StreamServerEvent) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *StreamServerEvent) GetSEvent() *anypb.Any {
	if x != nil {
		return x.SEvent
	}
	return nil
}

type RpcCreateRealmReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RealmCfgID string `protobuf:"bytes,1,opt,name=realmCfgID,proto3" json:"realmCfgID,omitempty"` //
	DsID       string `protobuf:"bytes,2,opt,name=dsID,proto3" json:"dsID,omitempty"`
}

func (x *RpcCreateRealmReq) Reset() {
	*x = RpcCreateRealmReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcCreateRealmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCreateRealmReq) ProtoMessage() {}

func (x *RpcCreateRealmReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCreateRealmReq.ProtoReflect.Descriptor instead.
func (*RpcCreateRealmReq) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *RpcCreateRealmReq) GetRealmCfgID() string {
	if x != nil {
		return x.RealmCfgID
	}
	return ""
}

func (x *RpcCreateRealmReq) GetDsID() string {
	if x != nil {
		return x.DsID
	}
	return ""
}

type RpcCreateRealmResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RpcHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *RpcCreateRealmResp) Reset() {
	*x = RpcCreateRealmResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcCreateRealmResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCreateRealmResp) ProtoMessage() {}

func (x *RpcCreateRealmResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCreateRealmResp.ProtoReflect.Descriptor instead.
func (*RpcCreateRealmResp) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *RpcCreateRealmResp) GetHeader() *RpcHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type RpcCreateRealmResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DsID       string `protobuf:"bytes,1,opt,name=dsID,proto3" json:"dsID,omitempty"`
	TeamID     string `protobuf:"bytes,2,opt,name=teamID,proto3" json:"teamID,omitempty"`
	RealmCfgID string `protobuf:"bytes,3,opt,name=realmCfgID,proto3" json:"realmCfgID,omitempty"` //
	DsAddr     string `protobuf:"bytes,4,opt,name=dsAddr,proto3" json:"dsAddr,omitempty"`
}

func (x *RpcCreateRealmResult) Reset() {
	*x = RpcCreateRealmResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcCreateRealmResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCreateRealmResult) ProtoMessage() {}

func (x *RpcCreateRealmResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCreateRealmResult.ProtoReflect.Descriptor instead.
func (*RpcCreateRealmResult) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *RpcCreateRealmResult) GetDsID() string {
	if x != nil {
		return x.DsID
	}
	return ""
}

func (x *RpcCreateRealmResult) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

func (x *RpcCreateRealmResult) GetRealmCfgID() string {
	if x != nil {
		return x.RealmCfgID
	}
	return ""
}

func (x *RpcCreateRealmResult) GetDsAddr() string {
	if x != nil {
		return x.DsAddr
	}
	return ""
}

type RpcCreateRealmInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DsID       string `protobuf:"bytes,1,opt,name=dsID,proto3" json:"dsID,omitempty"`
	TeamID     string `protobuf:"bytes,2,opt,name=teamID,proto3" json:"teamID,omitempty"`
	RealmCfgID string `protobuf:"bytes,3,opt,name=realmCfgID,proto3" json:"realmCfgID,omitempty"` //
}

func (x *RpcCreateRealmInfo) Reset() {
	*x = RpcCreateRealmInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcCreateRealmInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCreateRealmInfo) ProtoMessage() {}

func (x *RpcCreateRealmInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCreateRealmInfo.ProtoReflect.Descriptor instead.
func (*RpcCreateRealmInfo) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *RpcCreateRealmInfo) GetDsID() string {
	if x != nil {
		return x.DsID
	}
	return ""
}

func (x *RpcCreateRealmInfo) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

func (x *RpcCreateRealmInfo) GetRealmCfgID() string {
	if x != nil {
		return x.RealmCfgID
	}
	return ""
}

type RpcJoinRealmResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamID string `protobuf:"bytes,1,opt,name=teamID,proto3" json:"teamID,omitempty"` //
}

func (x *RpcJoinRealmResult) Reset() {
	*x = RpcJoinRealmResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcJoinRealmResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcJoinRealmResult) ProtoMessage() {}

func (x *RpcJoinRealmResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcJoinRealmResult.ProtoReflect.Descriptor instead.
func (*RpcJoinRealmResult) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *RpcJoinRealmResult) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

type RpcJoinRealmInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RpcJoinRealmInfo) Reset() {
	*x = RpcJoinRealmInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcJoinRealmInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcJoinRealmInfo) ProtoMessage() {}

func (x *RpcJoinRealmInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcJoinRealmInfo.ProtoReflect.Descriptor instead.
func (*RpcJoinRealmInfo) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{8}
}

var File_server_rpc_proto protoreflect.FileDescriptor

var file_server_rpc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x7a, 0x0a, 0x09, 0x52, 0x70, 0x63, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2b,
	0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x70, 0x63, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x45,
	0x72, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x72, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72,
	0x6d, 0x73, 0x67, 0x22, 0x28, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x72, 0x72, 0x45, 0x6e,
	0x75, 0x6d, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x65,
	0x71, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x22, 0x41, 0x0a,
	0x11, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x43, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x06, 0x43, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x22, 0x41, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x53, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x06, 0x53, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x22, 0x47, 0x0a, 0x11, 0x52, 0x70, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x6c,
	0x6d, 0x43, 0x66, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65,
	0x61, 0x6c, 0x6d, 0x43, 0x66, 0x67, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x73, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x73, 0x49, 0x44, 0x22, 0x3b, 0x0a, 0x12,
	0x52, 0x70, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x25, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x7a, 0x0a, 0x14, 0x52, 0x70, 0x63,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x73, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x73, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x12, 0x1e, 0x0a,
	0x0a, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x43, 0x66, 0x67, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x43, 0x66, 0x67, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x73, 0x41, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x73, 0x41, 0x64, 0x64, 0x72, 0x22, 0x60, 0x0a, 0x12, 0x52, 0x70, 0x63, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x73, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x73, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x6d,
	0x43, 0x66, 0x67, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x61,
	0x6c, 0x6d, 0x43, 0x66, 0x67, 0x49, 0x44, 0x22, 0x2c, 0x0a, 0x12, 0x52, 0x70, 0x63, 0x4a, 0x6f,
	0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x65, 0x61, 0x6d, 0x49, 0x44, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x70, 0x63, 0x4a, 0x6f, 0x69, 0x6e,
	0x52, 0x65, 0x61, 0x6c, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x32, 0x8e, 0x01, 0x0a, 0x0c, 0x47, 0x61,
	0x6d, 0x65, 0x44, 0x73, 0x63, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x12, 0x3e, 0x0a, 0x0b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x70, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x71,
	0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0b, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x70, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x71,
	0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x32, 0x53, 0x0a, 0x0c, 0x44, 0x73,
	0x61, 0x44, 0x73, 0x63, 0x41, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x12, 0x43, 0x0a, 0x0d, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_rpc_proto_rawDescOnce sync.Once
	file_server_rpc_proto_rawDescData = file_server_rpc_proto_rawDesc
)

func file_server_rpc_proto_rawDescGZIP() []byte {
	file_server_rpc_proto_rawDescOnce.Do(func() {
		file_server_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_rpc_proto_rawDescData)
	})
	return file_server_rpc_proto_rawDescData
}

var file_server_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_server_rpc_proto_goTypes = []interface{}{
	(RpcHeader_RoomErrEnum)(0),   // 0: pb.RpcHeader.RoomErrEnum
	(*RpcHeader)(nil),            // 1: pb.RpcHeader
	(*StreamClientEvent)(nil),    // 2: pb.StreamClientEvent
	(*StreamServerEvent)(nil),    // 3: pb.StreamServerEvent
	(*RpcCreateRealmReq)(nil),    // 4: pb.RpcCreateRealmReq
	(*RpcCreateRealmResp)(nil),   // 5: pb.RpcCreateRealmResp
	(*RpcCreateRealmResult)(nil), // 6: pb.RpcCreateRealmResult
	(*RpcCreateRealmInfo)(nil),   // 7: pb.RpcCreateRealmInfo
	(*RpcJoinRealmResult)(nil),   // 8: pb.RpcJoinRealmResult
	(*RpcJoinRealmInfo)(nil),     // 9: pb.RpcJoinRealmInfo
	(*anypb.Any)(nil),            // 10: google.protobuf.Any
}
var file_server_rpc_proto_depIdxs = []int32{
	0,  // 0: pb.RpcHeader.ret:type_name -> pb.RpcHeader.RoomErrEnum
	10, // 1: pb.StreamClientEvent.CEvent:type_name -> google.protobuf.Any
	10, // 2: pb.StreamServerEvent.SEvent:type_name -> google.protobuf.Any
	1,  // 3: pb.RpcCreateRealmResp.header:type_name -> pb.RpcHeader
	4,  // 4: pb.GameDscRealm.CreateRealm:input_type -> pb.RpcCreateRealmReq
	4,  // 5: pb.GameDscRealm.RemoveRealm:input_type -> pb.RpcCreateRealmReq
	2,  // 6: pb.DsaDscARealm.StreamService:input_type -> pb.StreamClientEvent
	5,  // 7: pb.GameDscRealm.CreateRealm:output_type -> pb.RpcCreateRealmResp
	5,  // 8: pb.GameDscRealm.RemoveRealm:output_type -> pb.RpcCreateRealmResp
	3,  // 9: pb.DsaDscARealm.StreamService:output_type -> pb.StreamServerEvent
	7,  // [7:10] is the sub-list for method output_type
	4,  // [4:7] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_server_rpc_proto_init() }
func file_server_rpc_proto_init() {
	if File_server_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamClientEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamServerEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcCreateRealmReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcCreateRealmResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcCreateRealmResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcCreateRealmInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcJoinRealmResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcJoinRealmInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_rpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_server_rpc_proto_goTypes,
		DependencyIndexes: file_server_rpc_proto_depIdxs,
		EnumInfos:         file_server_rpc_proto_enumTypes,
		MessageInfos:      file_server_rpc_proto_msgTypes,
	}.Build()
	File_server_rpc_proto = out.File
	file_server_rpc_proto_rawDesc = nil
	file_server_rpc_proto_goTypes = nil
	file_server_rpc_proto_depIdxs = nil
}
