// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: server_rpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcHeader_RoomErrEnum int32

const (
	RpcHeader_OK            RpcHeader_RoomErrEnum = 0
	RpcHeader_ReqParamError RpcHeader_RoomErrEnum = 1
)

// Enum value maps for RpcHeader_RoomErrEnum.
var (
	RpcHeader_RoomErrEnum_name = map[int32]string{
		0: "OK",
		1: "ReqParamError",
	}
	RpcHeader_RoomErrEnum_value = map[string]int32{
		"OK":            0,
		"ReqParamError": 1,
	}
)

func (x RpcHeader_RoomErrEnum) Enum() *RpcHeader_RoomErrEnum {
	p := new(RpcHeader_RoomErrEnum)
	*p = x
	return p
}

func (x RpcHeader_RoomErrEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcHeader_RoomErrEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_server_rpc_proto_enumTypes[0].Descriptor()
}

func (RpcHeader_RoomErrEnum) Type() protoreflect.EnumType {
	return &file_server_rpc_proto_enumTypes[0]
}

func (x RpcHeader_RoomErrEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcHeader_RoomErrEnum.Descriptor instead.
func (RpcHeader_RoomErrEnum) EnumDescriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{0, 0}
}

type RpcHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    RpcHeader_RoomErrEnum `protobuf:"varint,1,opt,name=ret,proto3,enum=pb.RpcHeader_RoomErrEnum" json:"ret,omitempty"`
	Errmsg string                `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
}

func (x *RpcHeader) Reset() {
	*x = RpcHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcHeader) ProtoMessage() {}

func (x *RpcHeader) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcHeader.ProtoReflect.Descriptor instead.
func (*RpcHeader) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RpcHeader) GetRet() RpcHeader_RoomErrEnum {
	if x != nil {
		return x.Ret
	}
	return RpcHeader_OK
}

func (x *RpcHeader) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type RpcCreateRealmReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RealmCfgID string `protobuf:"bytes,1,opt,name=realmCfgID,proto3" json:"realmCfgID,omitempty"` //
	TeamID     string `protobuf:"bytes,2,opt,name=teamID,proto3" json:"teamID,omitempty"`
}

func (x *RpcCreateRealmReq) Reset() {
	*x = RpcCreateRealmReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcCreateRealmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCreateRealmReq) ProtoMessage() {}

func (x *RpcCreateRealmReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCreateRealmReq.ProtoReflect.Descriptor instead.
func (*RpcCreateRealmReq) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RpcCreateRealmReq) GetRealmCfgID() string {
	if x != nil {
		return x.RealmCfgID
	}
	return ""
}

func (x *RpcCreateRealmReq) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

type RpcCreateRealmResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RpcHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *RpcCreateRealmResp) Reset() {
	*x = RpcCreateRealmResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcCreateRealmResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCreateRealmResp) ProtoMessage() {}

func (x *RpcCreateRealmResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCreateRealmResp.ProtoReflect.Descriptor instead.
func (*RpcCreateRealmResp) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RpcCreateRealmResp) GetHeader() *RpcHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type RpcJoinRealmReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RealmID string `protobuf:"bytes,1,opt,name=realmID,proto3" json:"realmID,omitempty"` //
}

func (x *RpcJoinRealmReq) Reset() {
	*x = RpcJoinRealmReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcJoinRealmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcJoinRealmReq) ProtoMessage() {}

func (x *RpcJoinRealmReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcJoinRealmReq.ProtoReflect.Descriptor instead.
func (*RpcJoinRealmReq) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *RpcJoinRealmReq) GetRealmID() string {
	if x != nil {
		return x.RealmID
	}
	return ""
}

type RpcJoinRealmResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RpcHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *RpcJoinRealmResp) Reset() {
	*x = RpcJoinRealmResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcJoinRealmResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcJoinRealmResp) ProtoMessage() {}

func (x *RpcJoinRealmResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcJoinRealmResp.ProtoReflect.Descriptor instead.
func (*RpcJoinRealmResp) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *RpcJoinRealmResp) GetHeader() *RpcHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type RpcQuickJoinRealmReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RealmCfgID string `protobuf:"bytes,1,opt,name=realmCfgID,proto3" json:"realmCfgID,omitempty"` //
	TeamID     string `protobuf:"bytes,2,opt,name=teamID,proto3" json:"teamID,omitempty"`
}

func (x *RpcQuickJoinRealmReq) Reset() {
	*x = RpcQuickJoinRealmReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcQuickJoinRealmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcQuickJoinRealmReq) ProtoMessage() {}

func (x *RpcQuickJoinRealmReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcQuickJoinRealmReq.ProtoReflect.Descriptor instead.
func (*RpcQuickJoinRealmReq) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *RpcQuickJoinRealmReq) GetRealmCfgID() string {
	if x != nil {
		return x.RealmCfgID
	}
	return ""
}

func (x *RpcQuickJoinRealmReq) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

type RpcQuickJoinRealmResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header     *RpcHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Pending    bool       `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"` //true 正在创建
	TeamID     string     `protobuf:"bytes,3,opt,name=teamID,proto3" json:"teamID,omitempty"`
	DsAddr     string     `protobuf:"bytes,4,opt,name=dsAddr,proto3" json:"dsAddr,omitempty"`
	RealmCfgID string     `protobuf:"bytes,5,opt,name=realmCfgID,proto3" json:"realmCfgID,omitempty"` //
}

func (x *RpcQuickJoinRealmResp) Reset() {
	*x = RpcQuickJoinRealmResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcQuickJoinRealmResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcQuickJoinRealmResp) ProtoMessage() {}

func (x *RpcQuickJoinRealmResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcQuickJoinRealmResp.ProtoReflect.Descriptor instead.
func (*RpcQuickJoinRealmResp) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *RpcQuickJoinRealmResp) GetHeader() *RpcHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RpcQuickJoinRealmResp) GetPending() bool {
	if x != nil {
		return x.Pending
	}
	return false
}

func (x *RpcQuickJoinRealmResp) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

func (x *RpcQuickJoinRealmResp) GetDsAddr() string {
	if x != nil {
		return x.DsAddr
	}
	return ""
}

func (x *RpcQuickJoinRealmResp) GetRealmCfgID() string {
	if x != nil {
		return x.RealmCfgID
	}
	return ""
}

type RpcQueryRealmListRealmReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RpcQueryRealmListRealmReq) Reset() {
	*x = RpcQueryRealmListRealmReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcQueryRealmListRealmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcQueryRealmListRealmReq) ProtoMessage() {}

func (x *RpcQueryRealmListRealmReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcQueryRealmListRealmReq.ProtoReflect.Descriptor instead.
func (*RpcQueryRealmListRealmReq) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{7}
}

type RpcQueryRealmListRealmResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RpcHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *RpcQueryRealmListRealmResp) Reset() {
	*x = RpcQueryRealmListRealmResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcQueryRealmListRealmResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcQueryRealmListRealmResp) ProtoMessage() {}

func (x *RpcQueryRealmListRealmResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcQueryRealmListRealmResp.ProtoReflect.Descriptor instead.
func (*RpcQueryRealmListRealmResp) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *RpcQueryRealmListRealmResp) GetHeader() *RpcHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type NotifyJoinRealmReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamID string `protobuf:"bytes,2,opt,name=teamID,proto3" json:"teamID,omitempty"`
}

func (x *NotifyJoinRealmReq) Reset() {
	*x = NotifyJoinRealmReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyJoinRealmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyJoinRealmReq) ProtoMessage() {}

func (x *NotifyJoinRealmReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyJoinRealmReq.ProtoReflect.Descriptor instead.
func (*NotifyJoinRealmReq) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *NotifyJoinRealmReq) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

type NotifyJoinRealmResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header     *RpcHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	TeamID     string     `protobuf:"bytes,2,opt,name=teamID,proto3" json:"teamID,omitempty"`
	RealmCfgID string     `protobuf:"bytes,3,opt,name=realmCfgID,proto3" json:"realmCfgID,omitempty"` //
	DsAddr     string     `protobuf:"bytes,4,opt,name=dsAddr,proto3" json:"dsAddr,omitempty"`
}

func (x *NotifyJoinRealmResp) Reset() {
	*x = NotifyJoinRealmResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyJoinRealmResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyJoinRealmResp) ProtoMessage() {}

func (x *NotifyJoinRealmResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyJoinRealmResp.ProtoReflect.Descriptor instead.
func (*NotifyJoinRealmResp) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *NotifyJoinRealmResp) GetHeader() *RpcHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *NotifyJoinRealmResp) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

func (x *NotifyJoinRealmResp) GetRealmCfgID() string {
	if x != nil {
		return x.RealmCfgID
	}
	return ""
}

func (x *NotifyJoinRealmResp) GetDsAddr() string {
	if x != nil {
		return x.DsAddr
	}
	return ""
}

type RpcCreateRealmResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DsID       string `protobuf:"bytes,1,opt,name=dsID,proto3" json:"dsID,omitempty"`
	TeamID     string `protobuf:"bytes,2,opt,name=teamID,proto3" json:"teamID,omitempty"`
	RealmCfgID string `protobuf:"bytes,3,opt,name=realmCfgID,proto3" json:"realmCfgID,omitempty"` //
	DsAddr     string `protobuf:"bytes,4,opt,name=dsAddr,proto3" json:"dsAddr,omitempty"`
}

func (x *RpcCreateRealmResult) Reset() {
	*x = RpcCreateRealmResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcCreateRealmResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCreateRealmResult) ProtoMessage() {}

func (x *RpcCreateRealmResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCreateRealmResult.ProtoReflect.Descriptor instead.
func (*RpcCreateRealmResult) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *RpcCreateRealmResult) GetDsID() string {
	if x != nil {
		return x.DsID
	}
	return ""
}

func (x *RpcCreateRealmResult) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

func (x *RpcCreateRealmResult) GetRealmCfgID() string {
	if x != nil {
		return x.RealmCfgID
	}
	return ""
}

func (x *RpcCreateRealmResult) GetDsAddr() string {
	if x != nil {
		return x.DsAddr
	}
	return ""
}

type RpcCreateRealmInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DsID       string `protobuf:"bytes,1,opt,name=dsID,proto3" json:"dsID,omitempty"`
	TeamID     string `protobuf:"bytes,2,opt,name=teamID,proto3" json:"teamID,omitempty"`
	RealmCfgID string `protobuf:"bytes,3,opt,name=realmCfgID,proto3" json:"realmCfgID,omitempty"` //
}

func (x *RpcCreateRealmInfo) Reset() {
	*x = RpcCreateRealmInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcCreateRealmInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCreateRealmInfo) ProtoMessage() {}

func (x *RpcCreateRealmInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCreateRealmInfo.ProtoReflect.Descriptor instead.
func (*RpcCreateRealmInfo) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *RpcCreateRealmInfo) GetDsID() string {
	if x != nil {
		return x.DsID
	}
	return ""
}

func (x *RpcCreateRealmInfo) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

func (x *RpcCreateRealmInfo) GetRealmCfgID() string {
	if x != nil {
		return x.RealmCfgID
	}
	return ""
}

type RpcJoinRealmResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamID string `protobuf:"bytes,1,opt,name=teamID,proto3" json:"teamID,omitempty"` //
}

func (x *RpcJoinRealmResult) Reset() {
	*x = RpcJoinRealmResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcJoinRealmResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcJoinRealmResult) ProtoMessage() {}

func (x *RpcJoinRealmResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcJoinRealmResult.ProtoReflect.Descriptor instead.
func (*RpcJoinRealmResult) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *RpcJoinRealmResult) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

type RpcJoinRealmInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RpcJoinRealmInfo) Reset() {
	*x = RpcJoinRealmInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcJoinRealmInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcJoinRealmInfo) ProtoMessage() {}

func (x *RpcJoinRealmInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcJoinRealmInfo.ProtoReflect.Descriptor instead.
func (*RpcJoinRealmInfo) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{14}
}

var File_server_rpc_proto protoreflect.FileDescriptor

var file_server_rpc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x7a, 0x0a, 0x09, 0x52, 0x70, 0x63, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x72, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x03, 0x72, 0x65, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x22, 0x28, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d,
	0x45, 0x72, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12,
	0x11, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x10, 0x01, 0x22, 0x4b, 0x0a, 0x11, 0x52, 0x70, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x6d,
	0x43, 0x66, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x61,
	0x6c, 0x6d, 0x43, 0x66, 0x67, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x22,
	0x3b, 0x0a, 0x12, 0x52, 0x70, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x6c,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x2b, 0x0a, 0x0f,
	0x52, 0x70, 0x63, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x49, 0x44, 0x22, 0x39, 0x0a, 0x10, 0x52, 0x70, 0x63,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x25, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x22, 0x4e, 0x0a, 0x14, 0x52, 0x70, 0x63, 0x51, 0x75, 0x69, 0x63, 0x6b,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a,
	0x72, 0x65, 0x61, 0x6c, 0x6d, 0x43, 0x66, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x43, 0x66, 0x67, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65,
	0x61, 0x6d, 0x49, 0x44, 0x22, 0xa8, 0x01, 0x0a, 0x15, 0x52, 0x70, 0x63, 0x51, 0x75, 0x69, 0x63,
	0x6b, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x25,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x73, 0x41, 0x64, 0x64,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x73, 0x41, 0x64, 0x64, 0x72, 0x12,
	0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x43, 0x66, 0x67, 0x49, 0x44, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x43, 0x66, 0x67, 0x49, 0x44, 0x22,
	0x1b, 0x0a, 0x19, 0x52, 0x70, 0x63, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x61, 0x6c, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x22, 0x43, 0x0a, 0x1a,
	0x52, 0x70, 0x63, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x70, 0x63, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x22, 0x2c, 0x0a, 0x12, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4a, 0x6f, 0x69, 0x6e, 0x52,
	0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x22,
	0x8c, 0x01, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65,
	0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x43,
	0x66, 0x67, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x6c,
	0x6d, 0x43, 0x66, 0x67, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x73, 0x41, 0x64, 0x64, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x73, 0x41, 0x64, 0x64, 0x72, 0x22, 0x7a,
	0x0a, 0x14, 0x52, 0x70, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x73, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x73, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65,
	0x61, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d,
	0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x43, 0x66, 0x67, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x43, 0x66, 0x67,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x73, 0x41, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x64, 0x73, 0x41, 0x64, 0x64, 0x72, 0x22, 0x60, 0x0a, 0x12, 0x52, 0x70,
	0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x73, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x73, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a,
	0x72, 0x65, 0x61, 0x6c, 0x6d, 0x43, 0x66, 0x67, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x43, 0x66, 0x67, 0x49, 0x44, 0x22, 0x2c, 0x0a, 0x12,
	0x52, 0x70, 0x63, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x70,
	0x63, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x32, 0xee,
	0x02, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x73, 0x63, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x12,
	0x3e, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x12, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61,
	0x6c, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x38, 0x0a, 0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x12, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x70, 0x63, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65,
	0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65,
	0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0e, 0x51, 0x75, 0x69,
	0x63, 0x6b, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x12, 0x18, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x70, 0x63, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61,
	0x6c, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x51, 0x75,
	0x69, 0x63, 0x6b, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x51, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x61, 0x6c, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x6d,
	0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4a,
	0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x71,
	0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4a, 0x6f, 0x69, 0x6e,
	0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x32,
	0x9e, 0x01, 0x0a, 0x0c, 0x44, 0x73, 0x61, 0x44, 0x73, 0x63, 0x41, 0x52, 0x65, 0x61, 0x6c, 0x6d,
	0x12, 0x49, 0x0a, 0x0f, 0x57, 0x61, 0x69, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x61, 0x6c, 0x6d, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x16, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x6c,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x43, 0x0a, 0x0d, 0x57,
	0x61, 0x69, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x12, 0x16, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x70, 0x63, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x4a, 0x6f, 0x69,
	0x6e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_rpc_proto_rawDescOnce sync.Once
	file_server_rpc_proto_rawDescData = file_server_rpc_proto_rawDesc
)

func file_server_rpc_proto_rawDescGZIP() []byte {
	file_server_rpc_proto_rawDescOnce.Do(func() {
		file_server_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_rpc_proto_rawDescData)
	})
	return file_server_rpc_proto_rawDescData
}

var file_server_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_server_rpc_proto_goTypes = []interface{}{
	(RpcHeader_RoomErrEnum)(0),         // 0: pb.RpcHeader.RoomErrEnum
	(*RpcHeader)(nil),                  // 1: pb.RpcHeader
	(*RpcCreateRealmReq)(nil),          // 2: pb.RpcCreateRealmReq
	(*RpcCreateRealmResp)(nil),         // 3: pb.RpcCreateRealmResp
	(*RpcJoinRealmReq)(nil),            // 4: pb.RpcJoinRealmReq
	(*RpcJoinRealmResp)(nil),           // 5: pb.RpcJoinRealmResp
	(*RpcQuickJoinRealmReq)(nil),       // 6: pb.RpcQuickJoinRealmReq
	(*RpcQuickJoinRealmResp)(nil),      // 7: pb.RpcQuickJoinRealmResp
	(*RpcQueryRealmListRealmReq)(nil),  // 8: pb.RpcQueryRealmListRealmReq
	(*RpcQueryRealmListRealmResp)(nil), // 9: pb.RpcQueryRealmListRealmResp
	(*NotifyJoinRealmReq)(nil),         // 10: pb.NotifyJoinRealmReq
	(*NotifyJoinRealmResp)(nil),        // 11: pb.NotifyJoinRealmResp
	(*RpcCreateRealmResult)(nil),       // 12: pb.RpcCreateRealmResult
	(*RpcCreateRealmInfo)(nil),         // 13: pb.RpcCreateRealmInfo
	(*RpcJoinRealmResult)(nil),         // 14: pb.RpcJoinRealmResult
	(*RpcJoinRealmInfo)(nil),           // 15: pb.RpcJoinRealmInfo
}
var file_server_rpc_proto_depIdxs = []int32{
	0,  // 0: pb.RpcHeader.ret:type_name -> pb.RpcHeader.RoomErrEnum
	1,  // 1: pb.RpcCreateRealmResp.header:type_name -> pb.RpcHeader
	1,  // 2: pb.RpcJoinRealmResp.header:type_name -> pb.RpcHeader
	1,  // 3: pb.RpcQuickJoinRealmResp.header:type_name -> pb.RpcHeader
	1,  // 4: pb.RpcQueryRealmListRealmResp.header:type_name -> pb.RpcHeader
	1,  // 5: pb.NotifyJoinRealmResp.header:type_name -> pb.RpcHeader
	2,  // 6: pb.GameDscRealm.CreateRealm:input_type -> pb.RpcCreateRealmReq
	4,  // 7: pb.GameDscRealm.JoinRealm:input_type -> pb.RpcJoinRealmReq
	6,  // 8: pb.GameDscRealm.QuickJoinRealm:input_type -> pb.RpcQuickJoinRealmReq
	8,  // 9: pb.GameDscRealm.QueryRealmList:input_type -> pb.RpcQueryRealmListRealmReq
	10, // 10: pb.GameDscRealm.NotifyJoinRealm:input_type -> pb.NotifyJoinRealmReq
	12, // 11: pb.DsaDscARealm.WaitCreateRealm:input_type -> pb.RpcCreateRealmResult
	14, // 12: pb.DsaDscARealm.WaitJoinRealm:input_type -> pb.RpcJoinRealmResult
	3,  // 13: pb.GameDscRealm.CreateRealm:output_type -> pb.RpcCreateRealmResp
	5,  // 14: pb.GameDscRealm.JoinRealm:output_type -> pb.RpcJoinRealmResp
	7,  // 15: pb.GameDscRealm.QuickJoinRealm:output_type -> pb.RpcQuickJoinRealmResp
	9,  // 16: pb.GameDscRealm.QueryRealmList:output_type -> pb.RpcQueryRealmListRealmResp
	11, // 17: pb.GameDscRealm.NotifyJoinRealm:output_type -> pb.NotifyJoinRealmResp
	13, // 18: pb.DsaDscARealm.WaitCreateRealm:output_type -> pb.RpcCreateRealmInfo
	15, // 19: pb.DsaDscARealm.WaitJoinRealm:output_type -> pb.RpcJoinRealmInfo
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_server_rpc_proto_init() }
func file_server_rpc_proto_init() {
	if File_server_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcCreateRealmReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcCreateRealmResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcJoinRealmReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcJoinRealmResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcQuickJoinRealmReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcQuickJoinRealmResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcQueryRealmListRealmReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcQueryRealmListRealmResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyJoinRealmReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyJoinRealmResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcCreateRealmResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcCreateRealmInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcJoinRealmResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcJoinRealmInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_rpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_server_rpc_proto_goTypes,
		DependencyIndexes: file_server_rpc_proto_depIdxs,
		EnumInfos:         file_server_rpc_proto_enumTypes,
		MessageInfos:      file_server_rpc_proto_msgTypes,
	}.Build()
	File_server_rpc_proto = out.File
	file_server_rpc_proto_rawDesc = nil
	file_server_rpc_proto_goTypes = nil
	file_server_rpc_proto_depIdxs = nil
}
